[#8] money-service 동시성 문제
f-lab-edu/my-pay pull request #10
Opened 2023-11-02 12:20 UTC by ieunji2

Redis의 Redisson 라이브러리를 사용하여 분산 락을 구현했습니다.

- 분산 락 적용 - MoneyDistributedLockService.java
  - 머니충전 - chargeMoneyWithLock()
  - 머니송금 - sendMoneyWithLock()
- 락의 키 - 지갑의 아이디로 설정
  - 머니충전 - 내 지갑 아이디
  - 머니송금 - 보내는 사람의 지갑 아이디, 받는 사람의 지갑 아이디

기타 변경 사항

- MoneyService.java 인터페이스로 변경
  - (분산 락 적용 전) MoneyServiceImpl.java
  - (분산 락 적용 후) MoneyServiceWithLockImpl.java
- 머니충전 메서드명 변경
  - saveMoney() -> chargeMoney()

2023-11-03 15:16 UTC, f-lab-justin requested changes
@ieunji2 
테스트를 엄청 열심히 작성하셨네요. 한번 고민해보시기 바랍니다.

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/config/redis/DistributedLockAop.java
> +        throw new RuntimeException("Failed to acquire lock");
@ieunji2 
일반적으로 런타임 익셉션을 던집니다만..
custom한 Exception을 만들어서 처리합니다. 

예를 들면 
class RedisException extends RuntimeException
등과 같이 특정 도메인에 대한 예외를 만들어서 처리합니다.

이렇게 처리하면 특정 도메인에 대한 예외처리를 그룹핑할 수 있어요!

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/domain/Transaction.java
> +    this.transactionStatus = TransactionStatus.ERROR;
@ieunji2 
좋습니다. 요렇게 String을 바로 쓰거나 magic number를 사용하기 보다는 Enum을 활용하시는 것이 좋습니다.

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/domain/Wallet.java
> +  public void subtractMoney(final BigInteger amount) {
@ieunji2 
동시성 이슈는 없을까요?

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/controller/MoneyController.java
> +  public WalletResponse chargeMoney(@Authenticated final Account account, @RequestBody final ChargeMoneyRequest request) {
@ieunji2 
service가 request와 response를 바로 사용하면 어떤 장점과 단점이 있을까요?

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyDistributedLockService.java
> +    wallet.addMoney(request.amount());
@ieunji2 
함수의 결과를 리턴받아서 사용하는게 아니라, void로 처리되는 객체의 상태를 변경하는 코드들이 많은 것 같은데..
어떤 장점과 단점이 있을까요?

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyDistributedLockService.java
> +      moneyTransactionService.executeCharge(wallet);
@ieunji2 
위에서 말씀드린 것과 이어지는데 moneyTransactionService의 executeCharge를 호출한 결과로transaction(success or fail)을 받으면 어떨까요?

2023-11-03 15:16 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +  WalletResponse createWallet(final Account account);
@ieunji2 
service에서 controller가 다루는 엔티티를 다루는건 어떤 장점과 단점이 있을까요??

2023-11-11 16:30 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/domain/Wallet.java
> +  public void subtractMoney(final BigInteger amount) {
Wallet 도메인의 balance 필드에 여러 요청이 동시에 접근할 수 없도록 wallet의 id를 락의 키로 사용하는 분산 락을 적용했습니다. 만약에 하나의 동일한 지갑에 대해 잔액을 변경하는 머니충전이나 머니송금 서비스가 동시에 여러번 발생하는 경우에는 해당 지갑에 대한 락을 먼저 획득한 요청이 처리되고 나머지 요청은 락을 획득할 때까지 대기합니다. 락이 해제되어야 다음 요청이 락을 획득할 수 있기 때문에 동일한 지갑에 동시에 접근할 수 없을 것 같습니다.

2023-11-11 17:21 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/controller/MoneyController.java
> +  public WalletResponse chargeMoney(@Authenticated final Account account, @RequestBody final ChargeMoneyRequest request) {
동일한 dto 객체를 공유하면 장점으로는 개발 초기에 불필요한 코드 중복 없이 빠르게 기능을 구현할 수 있을 것 같습니다.
단점으로는 controller와 service 간의 결합이 생겨서 request와 response에 변경이 생기는 경우 service 로직에도 영향을 미치기 때문에 유지보수하기 힘들 것 같습니다. 이제까지 단점에 대해서는 많이 생각해 보지 못해서 이번에 service 영역의 dto 객체를 새로 만들고 매핑 라이브러리를 사용해서 객체 간 매핑을 해봤는데요, service가 controller를 의존하지 않고 경계와 역할이 좀 더 명확해진 것 같아서 좋은 것 같습니다~!

2023-11-11 17:57 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/service/MoneyDistributedLockService.java
> +    wallet.addMoney(request.amount());
함수의 호출 시점에 결과가 필요하지 않다고 생각하는 경우(오류 없이 정상 작동하면 되는 함수의 경우)에는 void로 처리했는데요, 이런 경우는 불필요하게 코드를 복잡하게 만들 수 있을 것 같다고 생각했습니다. 그런데 이번에 다른 부분도 한번 살펴 봤는데 void로 처리한 게 이렇게 많은 줄을 몰랐습니다;;ㅎ

함수의 결과를 리턴 받아서 사용하면 
1. 함수의 동작을 더 명확히 알 수 있다.
2. 함수의 결과를 전달하여 재사용 할 수 있다.
3. 테스트 코드 작성할 때 함수의 결과로 검증하기 용이하다.

요런 많은 장점이 있는 것 같습니다~ 앞으로 함수를 만들 때는 이런 내용을 좀 더 인지하고 작성해야겠습니다~!

2023-11-11 18:09 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/service/MoneyDistributedLockService.java
> +      moneyTransactionService.executeCharge(wallet);
executeCharge() 호출하면 transaction success 저장까지 하나의 트랜잭션으로 가져가서 리턴을 반환하도록 개선을 해봤는데요,, finally가 없어진 것은 가독성 부분에서 나아진 것 같은데, 여전히 결과를 받아서 활용할 여지가 있는지는 잘 모르겠는 부분입니다!!

2023-11-11 18:12 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +  WalletResponse createWallet(final Account account);
위에 동일한 내용인 것 같아 위 답변으로 확인 부탁드립니다!

2023-11-14 13:24 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyDistributedLockService.java
> +      moneyTransactionService.executeCharge(wallet);
@ieunji2 만약에 executeCharge를 테스트한다면 어떻게 테스트할 수 있을까요??

2023-11-14 13:25 UTC, f-lab-justin approved these changes
@ieunji2 
고생하셨습니다! 머징하고 다음으로 가시지요!

2023-11-15 07:20 UTC, merged