[#7] 예외 처리
f-lab-edu/my-pay pull request #11
Opened 2023-11-23 11:55 UTC by ieunji2

API에 의한 예외 발생 시 일관된 형식의 응답을 내려주도록 구현했습니다.

- account-service, money-service, api-gateway
  - 에러 코드 정의 - ErrorCode.java
  - 에러 응답 객체 - ErrorResponse.java
  - 전역 에러 처리기 - GlobalExceptionHandler.java

2023-11-29 13:50 UTC, f-lab-justin requested changes
@ieunji2 
전반적으로 예외처리를 잘 정리하신 것 같아요. 

근데 커밋하나가 너무 커서 리뷰하기가 쉽지 않네요T.T
다음부터는 커밋을 작게 쪼개서 작성하시면 좋을 것 같아요.

2023-11-29 13:50 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +    assertThat(response.statusCode()).isEqualTo(ErrorCode.INVALID_INPUT_VALUE.getStatus());
@ieunji2 
먼가..indent가 안맞는거 같아요T.T
response는 statusCode고 ErrorCode에서는 status를 가져와서 비교하니 먼가 서로 전혀 다른 값을 비교하는 것처럼 보여집니다. 가능하면 이름을 맞춰보면 좋지 않을까요?

2023-12-10 10:58 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +    assertThat(response.statusCode()).isEqualTo(ErrorCode.INVALID_INPUT_VALUE.getStatus());
제가 생각한 status가 statusCode로 쓰이고 있었네요~ㅎ
code와 message도 좀 더 분명하게 errorCode와 errorMessage로 변경했습니다~!

2023-12-10 11:03 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +    assertThat(response.statusCode()).isEqualTo(ErrorCode.INVALID_INPUT_VALUE.getStatus());
@f-lab-justin 
앞으로 커밋 단위를 좀 더 신경써서 올리도록 하겠습니다!!

2024-01-12 03:55 UTC, f-lab-justin approved these changes
머징 가시지요!

2024-01-12 11:46 UTC, merged