Account 엔티티 설계 및 CRUD 기능 추가, Auth 엔티티 설계
f-lab-edu/my-pay pull request #2
Opened 2023-09-10 12:46 UTC by ieunji2

2023-09-11 14:58 UTC, f-lab-justin requested changes
@ieunji2 
코멘트 한번 살펴봐주세요~!

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  private LocalDateTime updatedAt;
@ieunji2 
모든 엔티티에 id, created_at, updated_at이 있을텐데 한번 묶어볼까요??

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/v1/controller/AccountController.java
> +  public AccountController(final AccountService accountService) {
@ieunji2 
요부분은 lombok으로 좀 더 세련되게 할 수 있을거 같은데요~ 한번 찾아보셔요~!

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/v1/dto/AccountResponse.java
> +public record AccountResponse(Long id, String name, String email, boolean isValid) {
@ieunji2 
오~ record를 사용하셨군요~! 혹시 어떤 의도로 사용하신 건지 설명해주실 수 있을까요??

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  public void modify(final String name, final String email, final boolean isValid) {
@ieunji2 
음..modify란 이름은 "수정"이란 광범위한 의미를 가지다 보니 어떤 동작을 하는 지 정확히 잘 모르겠어요. 생성자를 사용하지 않으신 이유가 있을거 같은데..좀 더 의미를 분명하게 할 수 있는 용어가 없을까요??

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/v1/repository/AccountAdapter.java
> +class AccountAdapter implements AccountPort {
@ieunji2 
먼가..hexagonal architecture의 향기가 나는 이름인데..폴더구조는 그렇지가 않네요 ㅎㅎ
의도가 어떻게 될까요??

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +    final var request = AccountSteps.계정등록요청_생성();
@ieunji2 
junit의 기능을 활용해서 공통화된 부분을 줄일 수 있는 방법은 없을까요??

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +  void 계정조회() {
@ieunji2 
테스트 이름을 잘 지으면 테스트를 돌리고 나서 이해하기 쉽고 깔끔합니다.
요 블로그 글이 잘 정리되어 있는데 한번 참고해보세요~!
https://covenant.tistory.com/270

2023-09-11 14:58 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
@ieunji2 
음..테스트 시에는 h2를 사용하면 cleanup이 따로 필요 없는데..혹시 사용해보셨나요??

2023-09-13 01:18 UTC, ieunji2 commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  private LocalDateTime updatedAt;
@f-lab-justin 모든 엔티티의 공통 속성인 id, created_at, updated_at은 BaseEntity 클래스로 묶어 관리하도록 수정했습니다.

2023-09-13 01:18 UTC, ieunji2 commented on account-service/src/main/java/com/hello/account/v1/controller/AccountController.java
> +  public AccountController(final AccountService accountService) {
@f-lab-justin 
lombok의 @RequiredArgsConstructor 어노테이션을 적용했습니다~!

2023-09-13 01:37 UTC, ieunji2 commented on account-service/src/main/java/com/hello/account/v1/dto/AccountResponse.java
> +public record AccountResponse(Long id, String name, String email, boolean isValid) {
@f-lab-justin 
record는 자바 16부터 공식 기능이 되었는데  데이터를 불변으로 다루고, compact canonical 생성자, 접근자 메서드, equals(), hashCode(), toString()을 기본으로 제공합니다. 그래서 데이터 전송 객체로 사용하면 불변 객체로 간단하게 만들 수 있는 것 같아서 사용했습니다..!

2023-09-13 01:53 UTC, ieunji2 commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  public void modify(final String name, final String email, final boolean isValid) {
@f-lab-justin 
동작을 나타내는 용어로는 updateAccount가 더 나을까요?? 생성자는 초기화하는 역할을 하기 때문에 수정 메서드를 따로 만드는 게 좋다고 생각했습니다.

2023-09-13 02:11 UTC, ieunji2 commented on account-service/src/main/java/com/hello/account/v1/repository/AccountAdapter.java
> +class AccountAdapter implements AccountPort {
@f-lab-justin 
처음에 테스트 먼저 작성할 때 메모리 디비로 구현 하다가 JPA로 바꾸면서 다형성을 지키면서 변경하려다보니 포트와 어댑터로 만들게 됐는데요... 이러고 보니 사실 service도 포트를 만들어야할 것 같고 그러다보면 패키지 구조도 바꿔야할 것 같고... 그러면 아예 헥사고날 아키텍처로 만들어야하나 고민하다가 너무 오래 걸릴 것 같아서 일단 디비만 포트와 어댑터 구조를 적용해보자고 생각했습니다~ㅠㅠ

2023-09-13 02:15 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +    final var request = AccountSteps.계정등록요청_생성();
@f-lab-justin 
계정 등록 하는 부분이 조회, 수정, 삭제 테스트 전에 공통적으로 수행되어야 해서 @BeforeEach를 적용했습니다~!

2023-09-13 02:25 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
> +  void 계정조회() {
@f-lab-justin 
블로그 참고해서 @DisplayName, @ParameterizedTest 적용해 봤습니다~ 테스트 이름을 좀 더 분명하게 지을 필요가 있을 것 같은데 좀 더 고민해봐야할 것 같아요.

2023-09-13 03:37 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
@f-lab-justin 
SpringBootTest 어노테이션으로 서버를 띄우고 RestAssured를 사용해서 Api 테스트를 진행하는데 cleanup을 하지 않으면 테스트가 깨집니다. BeforeEach에서 repository를 조회해서 deleteAll()하는 방식도 해봤는데 기본키 생성값은 초기화가 안돼서 실패했습니다. 그래서 좀 찾아보고 제가 이해한 내용은 스레드가 새로 만들어져서 롤백이 무의미하고 ApplicationContext도 캐싱되어서 격리가 잘 안된다...?입니다...

아래는 제가 참고한 블로그에 있는 내용입니다!
> https://tecoble.techcourse.co.kr/post/2020-09-15-test-isolation/
HTTP 클라이언트와 서버는 각각 다른 스레드에서 실행된다. 따라서 아무리 테스트 코드에 @Transactional 어노테이션이 있다고 하더라도 호출되는 쪽은 다른 스레드에서 새로운 트랜잭션으로 커밋하기 때문에 롤백 전략이 무의미해지는 것이다.

2023-09-14 16:30 UTC, f-lab-justin requested changes
@ieunji2 
확인 부탁드려요~!

2023-09-14 16:30 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  public void modify(final String name, final String email, final boolean isValid) {
@ieunji2 
보아하니 인자로 받은 값이 있으면 무조건 업데이트를 하는 것 같아요. 이는 새로운 객체를 만드는 것과 동일한 행동인것 같습니다. 
그래서 생성자와 코드가 거의 동일한데요.
따라서 굳이 함수를 따로 빼지 않고, 생성자를 쓰는 것이 의미에 맞는 것처럼 보이는데..어떻게 생각하세요??

2023-09-14 16:30 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/v1/repository/AccountAdapter.java
> +class AccountAdapter implements AccountPort {
@ieunji2 
넵! 코드의 의도와 상황을 설명할 수 있으면 됩니다. 
요 부분은 차차 변경해보아요!

2023-09-14 16:30 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
@ieunji2 
음..h2는 테스트마다 초기화가 되는데..상황이 다른걸까요??
https://taes-k.github.io/2021/04/05/spring-test-isolation-datasource/

2023-09-16 02:28 UTC, ieunji2 commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  public void modify(final String name, final String email, final boolean isValid) {
@f-lab-justin 
생각해보니 수정 기능을 만들 때 뭐를 수정한다가 명확히 없어서 무조건 인자를 다 받도록 해서 생성자와 동일하게 만들어진것 같습니다.
지금은 새로운 객체를 만드는 것과 동일한 행동이지만 생성자를 쓰게되면 id가 새로 생성돼서 update가 아닌 insert를 수행하게 됩니다.

만약에 수정 기능이 이름을 수정한다라고 하면 이때는 `updateName(String name){}` 이런 식으로 따로 만드는 게 맞는걸까요?

2023-09-16 02:53 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/DatabaseCleanup.java
> +public class DatabaseCleanup implements InitializingBean {
현재 h2로 테스트가 돌아가고 있는데요. 테스트를 개별적으로 실행하면 테스트마다 초기화가 되는데 `All Tests`를 실행하면 현재 제가 작성한 테스트 코드가 테스트마다 계정 등록을 수행하면서 id 값이 새로 생성되어 버려서 테스트가 깨지는 현상인 것 같습니다. 테스트 코드를 작성할 때 등록한 것을 조회하는 방식으로 하면 현재는 문제가 없을 것 같은데 나중에 비즈니스가 복잡해지고 테스트도 복잡해졌을 떄는 테스트마다 db가 clean하면 좋을 것 같아서 위 방식을 사용해봤는데요. 이 부분은 아직 잘 모르겠어서 좀 더 찾아봐야할 것 같습니다.

2023-09-17 14:36 UTC, f-lab-justin commented on account-service/src/main/java/com/hello/account/domain/Account.java
> +  public void modify(final String name, final String email, final boolean isValid) {
@ieunji2 
멘토링 시간에 같이 이야기해서 정리했습니다~
현재 필드가 적어서 동일한 로직의 중복으로 보여졌었는데요. 이미 존재하는 객체의 업데이트를 한다고 하면 선택적으로 업데이트했었을 거라 중복으로 보이지 않았을 거 같습니다!

2023-09-17 14:37 UTC, f-lab-justin approved these changes
@ieunji2 
고생하셨습니다~! 다음 단계로 가보아요!!

2023-09-20 14:16 UTC, merged