부하 테스트에서 발견된 동시성 문제 해결
f-lab-edu/my-pay pull request #26
Opened 2024-05-19 12:51 UTC by ieunji2

관련 이슈 내용입니다.

#20 - 여러 트랜잭션이 기존에 동작하고 있는 영속성 컨텍스트를 공유해서 발생하는 문제로 osiv를 false로 설정해서 해결했습니다.
#21 - 머니 송금 엣지케이스(A -> B, B->A 서로 간에 동시 요청) 데드락 문제는 레디슨의 멀티락 획득이 원자적이지 않아서 생기는 문제로, 락 획득 요청을 지갑 아이디 순으로 정렬해서 해결했습니다.
- 수정 전: Thread 1 - [LOCK:1, LOCK:2], Thread 2 - [LOCK:2, LOCK1]
- 수정 후: Thread 1 - [LOCK:1, LOCK:2], Thread 2 - [LOCK:1, LOCK2]

#22 - 락의 범위를 잔액 조회 및 업데이트로 줄이고 락의 범위를 트랙잭션 경계로 잡았습니다.

2024-06-23 13:53 UTC, f-lab-justin requested changes
@ieunji2 
확인 부탁드립니다!

2024-06-23 13:53 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/config/redis/CustomDistributedLockAop.java
> +    return distributedLock.keys().length == 1;
@ieunji2 
애플리케이션 로직에서 꼭 필수값으로 처리한다고 하더라도..여기서 0인 케이스를 처리해두면 좋을 것 같습니다! 절대 0이 나오지 않아야 한다면 exception처리를 명확히 해두는 것도 좋을 것 같습니다.

2024-06-23 13:53 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/config/redis/DistributedLock.java
> +  long leaseTime() default 5L;
@ieunji2 
다른 설정값과 연관되어 있는 설정값은 최대한 바깥으로 빼서 한곳에서 설정하는 것이 알기 쉽습니다.
추가적으로 절대적으로 지켜져야 하는 값이면 validation까지 들어가줘도 좋을 것 같아요~!

2024-06-23 13:53 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/config/redis/DistributedMultiLock.java
> +  long leaseTime() default 5L;
@ieunji2 
여기도 위와 같습니다~!

2024-06-23 13:53 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyTransactionService.java
> +    walletPort.saveWallet(receiverWallet.addMoney(amount));
@ieunji2 
람다를 쓰거나 Strategy Pattern을 활용해서 개선할 수는 없을지 한번 고민해봅시다.

2024-07-05 19:21 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/config/redis/CustomDistributedLockAop.java
> +    return distributedLock.keys().length == 1;
분산락의 키의 수는 절대 0이 나오면 안 되기 때문에 예외 처리를 추가했습니다.

2024-07-05 19:29 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/config/redis/DistributedLock.java
> +  long leaseTime() default 5L;
분산락의 타임아웃 설정은 AopForTransaction 클래스의 트랜잭션 타임아웃과 연관되어 있어서 application.yml에서 관리하도록 변경했습니다. 

분산락 내에서 동작하는 트랜잭션의 timeout은 분산락의 leaseTime 보다 작아야 하기 떄문에 validation은 AopForTransaction 클래스에 추가했습니다!

2024-07-05 19:39 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/service/MoneyTransactionService.java
> +    walletPort.saveWallet(receiverWallet.addMoney(amount));
람다를 사용해서 동일한 동작을 executeTransaction()로 분리했습니다.
중복이 제거되면서 코드가 조금 간결해진 것 같아 보기 좋은 것 같습니다~!

2024-07-07 14:49 UTC, f-lab-justin approved these changes
가독성과 관련된 영역은 참고하시고, 머징하고 다음으로 가도 좋을 것 같습니다!

2024-07-07 14:49 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyTransactionService.java
> +  }
{ 
   Transaction receiverTransaction = executeTransaction(receiverWallet, receiverTransaction, Wallet::addMoney);
   Transaction senderTransaction = executeTransaction(senderWallet, senderTransaction, Wallet::subtractMoney);
   
   return senderTransaction; 
}

2024-07-11 15:57 UTC, merged