account-service db 로컬 환경 연동, api 문서화 restdocs 적용
f-lab-edu/my-pay pull request #4
Opened 2023-09-24 10:12 UTC by ieunji2

2023-09-24 13:50 UTC, f-lab-justin requested changes

2023-09-24 13:50 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
>      assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
@ieunji2 
테스트 케이스 내에서 최대한 테스트의 내용은 보이는 것이 좋을 것 같아요~

```
// Given
- 상황 만들기

// When
- 실제 테스트하고자 하는 함수 혹은 API 호출

// Then
- 결과 리턴 받아서 assert의 구문들..
```

2023-09-24 13:50 UTC, f-lab-justin commented on account-service/src/test/java/com/hello/account/SnippetsConstants.java
> +  public static final String IDENTIFIER = "{class-name}/{method-name}";
@ieunji2 
굿입니다요~!

2023-09-24 13:50 UTC, f-lab-justin commented on account-service/src/main/resources/application.yml
> +      ddl-auto: create
@ieunji2 
요부분은 조심해야합니다~
phase에 대해서 고민해보시죠! 
profile : local, (dev), sandbox, beta, production.

그래서 일반적으로는 "test" profile에 create-drop을 넣고 진행합니다.

2023-09-24 13:50 UTC, f-lab-justin commented on account-service/src/main/resources/application.yml
> +    username: myuser
@ieunji2 
요즘은 vault와 같이 별도의 키 저장소를 활용해서 데이터를 가져옵니다.
요번 프로젝트 때에는 크게 중요하지 않지만 한번 살펴보시면 좋을듯요~!

2023-09-26 08:34 UTC, ieunji2 commented on account-service/src/test/java/com/hello/account/AccountApiTest.java
>      assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
@f-lab-justin 
테스트 내용이 파일 내에서 보이도록 수정했습니다~!

2023-09-26 10:27 UTC, ieunji2 commented on account-service/src/main/resources/application.yml
> +      ddl-auto: create
@f-lab-justin 
일단 test와 local로 분리했습니다~

2023-10-01 14:41 UTC, f-lab-justin approved these changes

2023-10-01 14:41 UTC, merged