[#5] money-service 기능 구현
f-lab-edu/my-pay pull request #6
Opened 2023-10-06 16:04 UTC by ieunji2

머니 서비스 기능 구현입니다.

- MoneyService.java

  - 지갑생성 - createWallet()
  - 지갑조회 - getWallet()
  - 머니충전 - addMoney()
  - 머니송금 - sendMoney()

테스트부터 작성해 봤는데 아직 예외 처리가 잘 안되어 있어서 예외 케이스에 대한 테스트를 작성하지 못했습니다.

많은 피드백 부탁드립니다~!

2023-10-08 03:12 UTC, f-lab-justin requested changes
@ieunji2 
확인 부탁드립니다!

2023-10-08 03:12 UTC, f-lab-justin commented on api-gateway/src/main/java/com/hello/apigateway/config/AppConfig.java
> +  public RestTemplate getRestTemplate() {
@ieunji2 
함수 이름 변경의 고민이 있었을거 같은데 이유를 알 수 있을까요??

2023-10-08 03:12 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/controller/MoneyController.java
> +    final Long accountId = Long.valueOf(decode(xAccountId));
@ieunji2
도메인에서의 assert는 사용이 이상하지 않은데..request의 assert는 spring에서 제공하는 다양한 방법으로 처리가 가능할거 같아요.accountId 관련 처리의 중복도 해결할 수 있구요.

argumentResolver를 한번 살펴보세요!

2023-10-08 03:12 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/dto/AccountResponse.java
> +    Assert.notNull(id, "계정 ID는 필수입니다.");
@ieunji2 
Request나 Response는 보통 json으로의 serialize/deserialize이기 때문에 다른 방식으로 깔끔하게 에러처리를 할 수 있을거 같은데 한번 살펴보세요~!

2023-10-08 03:12 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/repository/TransactionAdapter.java
> +  TransactionAdapter(final TransactionRepository transactionRepository) {
@ieunji2 
혹시 lombok을 사용하지 않는 이유가 있을까요??

2023-10-08 03:12 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +  private Wallet getWallet(final SendMoneyRequest request) {
@ieunji2 
위의 wallet과 아래 wallet은 동작이 거의 유사하네요. 하나로 합치면서 변경된 내용만 처리할 수 있게 할수는 없을까요??

2023-10-08 03:12 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +
@ieunji2 
sender와 receiver의 동작이 거의 동일한데요. 
이 부분도 좀 더 과정이 잘 보일 수 있도록 리팩토링을 할 수 있을까요?

2023-10-08 03:12 UTC, f-lab-justin commented on money-service/src/test/java/com/hello/money/MoneyServiceTest.java
> +public class MoneyServiceTest {
@ieunji2 
sendMoneyTest가 없는거 같아요. 질문 주신 내용들을 테스트로 한번 작성해보세요!
```
MoneyService.java 에서 트랜잭션 처리를 위해 addMoney(), sendMondy() 메서드에 @Transactional 어노테이션을 걸고 executeUpdate()에서 예외가 발생하면 예외를 던지는 방식으로 처리했는데 괜찮을까요?
```

https://f-lab-edu.slack.com/archives/C04QHEMAYDC/p1696644914216579?thread_ts=1696167254.280599&cid=C04QHEMAYDC

2023-10-08 13:54 UTC, f-lab-justin requested changes

2023-10-08 13:54 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +
@ieunji2 
멘토링에서 이야기한대로 트랜젝션의 경계를 잘 고민해보세요~!
두개의 executeUpdate가 하나의 트랜젝션으로 묶이고, 실패 시 exception을 받아 실패 내역을 저장하는게 의도하신 로직인거 같아요~!

2023-10-19 01:01 UTC, ieunji2 commented on api-gateway/src/main/java/com/hello/apigateway/config/AppConfig.java
> +  public RestTemplate getRestTemplate() {
@f-lab-justin 
동작을 표현하려고 함수 이름을 고친 것 같습니다. 그런데 이 부분은... 빈을 생성하기 위한 설정 정보로 메서드명이 빈의 이름이 되므로 `restTemplate()`이 더 적절한 것 같아서 다시 변경했습니다~!

2023-10-19 01:29 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/controller/MoneyController.java
> +    final Long accountId = Long.valueOf(decode(xAccountId));
@f-lab-justin 
argumentResolver를 적용해서 중복되는 부분 해결했습니다~!

2023-10-19 01:55 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/dto/AccountResponse.java
> +    Assert.notNull(id, "계정 ID는 필수입니다.");
@f-lab-justin 
찾아보니 `hibernate-validator` api 를 사용하는 방법도 있는 것 같네요.
저는 위 방식은 사용해보지 않아서 단순히 유효하지 않은 값에 대해 `IllegalArgumentException`을 받아 예외 처리를 하려고 했는데요, 혹시 추천하는 다른 방식이 있으신가요??

2023-10-19 02:01 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/repository/TransactionAdapter.java
> +  TransactionAdapter(final TransactionRepository transactionRepository) {
@f-lab-justin 
아니요~! lombok 좋아합니다. 
다만 처음에 코드 작성할 때는 잘 안쓰고 리팩토링 하면서 적용하는 편인데 이부분은 놓친 것 같습니다!

2023-10-19 02:11 UTC, ieunji2 commented on money-service/src/test/java/com/hello/money/MoneyServiceTest.java
> +public class MoneyServiceTest {
@f-lab-justin 
sendMoney 테스트 작성해 보았습니다~!
테스트를 작성하지 않았다면 `동일한_Bean_안에_상위_메서드가_Transactional_어노테이션이_없으면_하위에는_선언이_되어_있어도_전이되지_않는다()`와 같은 케이스를 놓칠 뻔 했습니다..😂

2023-10-19 02:31 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +
@f-lab-justin 
말씀주신 내용처럼  `executeSend()`로 하나의 트랜잭션으로 묶고, 트랜잭션 적용을 위해 `MoneyTransactionService.java`로 분리해서 빈으로 등록하는 방식으로 코드를 다시 작성했습니다.

2023-10-19 02:47 UTC, ieunji2 commented on money-service/src/main/java/com/hello/money/v1/service/MoneyService.java
> +
> @ieunji2 sender와 receiver의 동작이 거의 동일한데요. 이 부분도 좀 더 과정이 잘 보일 수 있도록 리팩토링을 할 수 있을까요?

@f-lab-justin 리팩토링을 잘못했는지 진행한 결과가 코드가 잘 안읽혀서 우선 `saveMoney()`와 `sendMoney()`메서드 안의 내용을 분리하지 않고 다시 작성하여 주석을 달아놓았습니다. 동작이 거의 동일하지만 조금씩 다른 부분이 있어서 어떻게 잘 리팩토링 할 수 있을지 같이 한번 얘기해 보면 좋을 것 같습니다~!

2023-10-19 15:40 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/dto/AccountResponse.java
> +    Assert.notNull(id, "계정 ID는 필수입니다.");
@ieunji2 
Spring validator도 있습니다^^ 한번 살펴보세요!

2023-10-19 15:46 UTC, f-lab-justin approved these changes
@ieunji2 
고생하셨습니다!
PR이 좀 길어지는 데 일단 머징하고 진행해도 될 것 같아요~!

2023-10-19 15:46 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/domain/Transaction.java
> +    this.transactionStatus = "요청";
@ieunji2 
status와 같은 내용은 enum값으로 설정하는 것을 고려해보세요!

2023-10-19 15:46 UTC, f-lab-justin commented on money-service/src/main/java/com/hello/money/v1/controller/MoneyController.java
> +@RequestMapping("/v1/moneys")
@ieunji2 
money는 복수를 쓸 수 없어요~ 참고 부탁드립니다~!

2023-10-22 13:38 UTC, merged